const wrangler_api  = require("./Wrangler")
const jack_jones_api = require("./jack&jones")
const Tommy_api=require("./Tommy")
const Levis_api = require("./levis")
const Spykar_api= require("./Spykar")
const marksandspencer = require("./Mark_spencer")
const US_polo_api = require("./US_polo")
const Lee_api = require("./Lee")
const American_eagle_api = require("./American_eagle")
const Blackberrys_api = require("./blackberrys")
const Gas_api = require("./Gas")
const United_api = require("./UnitedColors")
const RareRabbit_api = require("./RareRabbit")
const Calvin_api = require("./Calvin")
const Diesel_api = require("./Diesel")


const router = require("express").Router()

router.post("/Wrangler",wrangler_api)
router.post("/United",United_api)
router.post("/Jack_Jones",jack_jones_api)
router.post("/Tommy",Tommy_api)
router.post("/Levis",Levis_api)
router.post("/Spykar",Spykar_api)
router.post('/Markspencer',marksandspencer)
router.post("/USpolo",US_polo_api)
router.post("/Lee",Lee_api)
router.post("/a-eagle",American_eagle_api)
router.post("/blackberrys",Blackberrys_api)
router.post("/Gas",Gas_api)
router.post("/rarerabbit",RareRabbit_api)
router.post("/Calvin",Calvin_api)
router.post("/Diesel",Diesel_api)
module.exports = router